### ISSUE TITLE
Needs Tests

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/tweet-sentiment#1]

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by JimCampagno** [comment]
Deadline: 9/4/15 (Friday)

**Comment by AnnJohn** [comment]
Hey @JimCampagno was this fixed? If not, could you set a new deadline? Thanks

**Comment by JimCampagno** [comment]
@AnnJohn New Deadline will be Friday 9/11/15.  I'll be working on the Learn iOS App today & tomorrow.

**Comment by JimCampagno** [comment]
@AnnJohn Pushing deadline to Thursday September 17th.  Ill be working on learn iOS App from the 14th-16th.  The solution is complete on this lab - need to review how I put together tests with Tim/Joe next week.

**Comment by AnnJohn** [comment]
@JimCampagno Got it, thanks!
